apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: fidget-spinner-helm
  template:
    metadata:
      labels:
        name: fidget-spinner-helm
    spec:
      containers:
      - image: {{ .Values.image }}
        name: pause
        resources:
          limits:
            memory: {{ .Values.memory }}
          requests:
            memory: {{ .Values.memory }}
